restaurant_pipeline:
  target: airflow
  outputs:
    airflow:
      type: postgres
      host: postgres-db
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: analytics


